baseURL = "https://gamebucket.onrender.com"
languageCode = "ua-UA"
title = "Game Bucket"
theme = "hyde-hyde"


# Number of blog posts in each pagination page
paginate = 6

[permalinks]
# Configures post URLs
post = "/blog/:year-:month-:day-:title/"


[params]
  mainSections = ["pokemongo", "retronews"]

[[menu.main]]
  Name = "Blog"
  URL = "/"
  weight = -10

[[menu.main]]
  Name = "Pokemon GO"
  URL = "/pokemongo/"
  identifier = "pokemongo"
  weight = -5

[[menu.main]]
  Name = "Retro gaming"
  URL = "/retrogaming/"
  identifier = "retrogaming"
  weight = -4

[params.social]
  twitter = "b3ntuz1"
  telegram = "pokemonews"